#:schema node_modules/wrangler/config-schema.json
name = "rate"
main = "backend.js"
compatibility_date = "2024-12-24"
compatibility_flags = ["nodejs_compat"]

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

[env.production]
account_id = "0a54c51ce4290ec2bb59f10871e4e25d"
workers_dev = true

[[kv_namespaces]]
binding = "rate"
id = "c28baadd734c4edf85d40b9746e88e78"